# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegisterAccountCompleteValidation():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerAccountCompleteValidation(self):
    self.vars["validFirstName"] = "John"
    self.vars["validLastName"] = "Doe"
    self.vars["validEmail"] = "john.doe.test@gmail.com"
    self.vars["validPhone"] = "1234567890"
    self.vars["validPassword"] = "SecurePass123"
    self.vars["longString"] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567"
    self.vars["address1"] = "123 Main Street"
    self.vars["city"] = "New York"
    self.vars["postCode"] = "10001"
    self.driver.get("http://demo.opencart.com//")
    assert self.driver.title == "Your Store"
    self.driver.find_element(By.XPATH, "//span[text()=\'My Account\']").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Register Account"
    self.driver.find_element(By.CSS_SELECTOR, ".btn.btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert-danger").text == "Warning: You must agree to the Privacy Policy!"
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn.btn-primary").click()
    time.sleep(2)
    time.sleep(1)
    self.driver.get("http://demo.opencart.com//index.php?route=account/register")
    time.sleep(2)
    time.sleep(2)
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn.btn-primary").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h1")
    assert len(elements) > 0
  
