# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestSeleniumBasics():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testSeleniumBasics(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1920, 1080)
    self.vars["pageTitle"] = self.driver.execute_script("return document.title")
    print("Page Title: {}".format(self.vars["pageTitle"]))
    self.vars["pageURL"] = self.driver.execute_script("return window.location.href")
    print("Current URL: {}".format(self.vars["pageURL"]))
    assert self.driver.title == "OrangeHRM"
  
