# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait

class TestBrowserNavigationTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_browserNavigationTest(self):
    self.driver.get("https://tutorialsninja.com/demo/")

    WebDriverWait(self.driver, 30).until(lambda d: d.title)
    self.vars["title1"] = self.driver.title
    print(f"Step 1 - Initial Page Title: {self.vars['title1']}")

    self.driver.get("https://tutorialsninja.com/demo/index.php?route=account/register")

    WebDriverWait(self.driver, 30).until(lambda d: "route=account/register" in d.current_url)
    WebDriverWait(self.driver, 30).until(lambda d: d.title)
    self.vars["title2"] = self.driver.title
    print(f"Step 2 - Second Page Title: {self.vars['title2']}")

    self.vars["backResult"] = self.driver.execute_script("window.history.back(); return \'back executed\';")

    WebDriverWait(self.driver, 30).until(lambda d: d.title)
    self.vars["title3"] = self.driver.title
    print(f"Step 3 - After back() Title: {self.vars['title3']}")

    self.vars["forwardResult"] = self.driver.execute_script("window.history.forward(); return \'forward executed\';")

    WebDriverWait(self.driver, 30).until(lambda d: d.title)
    self.vars["title4"] = self.driver.title
    print(f"Step 4 - After forward() Title: {self.vars['title4']}")

    self.vars["refreshResult"] = self.driver.execute_script("window.location.reload(); return \'refresh executed\';")

    WebDriverWait(self.driver, 30).until(lambda d: d.title)
    self.vars["title5"] = self.driver.title
    print(f"Step 5 - After refresh() Title: {self.vars['title5']}")
    print("========================================")
    print("✓ Browser Navigation Test Completed! Browser will be closed.")
  
