# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTc004():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tc004(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(1458, 696)
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Qafox.com").click()
    time.sleep(2000)
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    time.sleep(2000)
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.ID, "grid-view")))
    self.driver.find_element(By.ID, "input-sort").click()
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    time.sleep(3000)
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".image .img-responsive")))
    self.driver.find_element(By.CSS_SELECTOR, ".image .img-responsive").click()
    time.sleep(3000)
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.ID, "button-cart")))
    self.driver.find_element(By.ID, "button-cart").click()
    self.driver.find_element(By.NAME, "search").click()
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.NAME, "search")))
    self.driver.find_element(By.NAME, "search").send_keys("Mobile")
    time.sleep(500)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
    time.sleep(3000)
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.NAME, "search")))
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.ID, "input-search").click()
    self.driver.find_element(By.ID, "input-search").send_keys("Mobile")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "button-search").click()
  
